[package]
name = "soldb-dap"
version.workspace = true
edition.workspace = true
description = "Debug Adapter Protocol server for SolDB, the ETHDebug-first Solidity debugger"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories = ["development-tools::debugging", "command-line-utilities"]

[lib]
doctest = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
soldb-core.workspace = true
soldb-debugger.workspace = true
soldb-ethdebug.workspace = true
soldb-repl.workspace = true
soldb-rpc.workspace = true

[[bin]]
name = "soldb-dap-server"
path = "src/main.rs"

[lints]
workspace = true
