name: Rust

on:
  push:
    branches: [main]
    paths:
      - "rust/**"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: [main]
    paths:
      - "rust/**"
      - ".github/workflows/rust.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
