[package]
name = "soldb-profiler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
serde.workspace = true
soldb-core = { path = "../soldb-core" }
soldb-ethdebug = { path = "../soldb-ethdebug" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
